### ISSUE TITLE
No Internet Connection, No Weight Files

### ISSUE THREAD

**Issue by asoroosh** [ANTsRNet/BrainExtraction#3]
Hi Folks, 

Is there any chance that one could get the weight files without the internet connection? I am running the `doBrainExtraction.py` on a cluster which its compute nodes are isolated from the internet. And I bump into the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.25.6-py3.6.egg/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.25.6-py3.6.egg/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.25.6-py3.6.egg/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.25.6-py3.6.egg/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.25.6-py3.6.egg/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x2af323fbb400>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests-2.22.0-py3.6.egg/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.25.6-py3.6.egg/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.25.6-py3.6.egg/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ndownloader.figshare.com', port=443): Max retries exceeded with url: /files/13729661 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2af323fbb400>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/well/nvs-mri-temp/users/scf915/BrainExtraction/Scripts/doBrainExtraction.py", line 52, in <module>
    weights_file_name = antspynet.get_pretrained_network("brainExtraction", weights_file_name)
  File "/usr/local/lib/python3.6/site-packages/antspynet-0.0-py3.6.egg/antspynet/utilities/get_pretrained_network.py", line 79, in get_pretrained_network
    r = requests.get(url)
  File "/usr/local/lib/python3.6/site-packages/requests-2.22.0-py3.6.egg/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests-2.22.0-py3.6.egg/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests-2.22.0-py3.6.egg/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests-2.22.0-py3.6.egg/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests-2.22.0-py3.6.egg/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ndownloader.figshare.com', port=443): Max retries exceeded with url: /files/13729661 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2af323fbb400>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

Thank you so much in advance,

**Comment by ntustison** [comment]
Just download the weights file from [here](https://ndownloader.figshare.com/files/13729661) and put it wherever you need it to be.  Then simply place the name of the file [here](https://github.com/ANTsXNet/BrainExtraction/blob/master/Scripts/doBrainExtraction.py#L49).

**Comment by asoroosh** [comment]
Thanks! 
However, I bump into the following error. 
```
Traceback (most recent call last):
  File "/some/kindof/home/directory/BrainExtraction/Scripts/doBrainExtraction.py", line 54, in <module>
    unet_model.load_weights(weights_file_name)
  File "/usr/local/lib/python3.6/site-packages/Keras-2.3.1-py3.6.egg/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/Keras-2.3.1-py3.6.egg/keras/engine/network.py", line 1230, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.6/site-packages/Keras-2.3.1-py3.6.egg/keras/engine/saving.py", line 1224, in load_weights_from_hdf5_group
    reshape=reshape)
  File "/usr/local/lib/python3.6/site-packages/Keras-2.3.1-py3.6.egg/keras/engine/saving.py", line 980, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "<__array_function__ internals>", line 6, in transpose
  File "/usr/local/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 650, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/usr/local/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
```
Just as a background, I have the ANTsPyNet as singularity container and my Keras version is `2.3.1`.

**Comment by ntustison** [comment]
Can you show the entire screen dump starting with the actual command?

**Comment by asoroosh** [comment]
Here is the call:
```
singularity run -B /directory/the/to/data/${StudyID} \
/apps/singularity/antspynet-0.0.3.sif \
${PATH2BRAINEXTRACTION}/BrainExtraction/Scripts/doBrainExtraction.py \
${NonLinSSTDirImg}.nii.gz \
${BrainMask}.nii.gz \
${PATH2BRAINEXTRACTION}/BrainExtraction/Data/Template/S_template3_resampled.nii.gz
```

And here is my log:
```
2019-11-08 12:20:45.255690: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-11-08 12:20:45.261806: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2600000000 Hz
2019-11-08 12:20:45.263188: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x14358190 executing computations on platform Host. Devices:
2019-11-08 12:20:45.263228: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
Using TensorFlow backend.
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/some/kindof/directory/BrainExtraction/Scripts/doBrainExtraction.py", line 54, in <module>
    unet_model.load_weights(weights_file_name)
  File "/usr/local/lib/python3.6/site-packages/Keras-2.3.1-py3.6.egg/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/Keras-2.3.1-py3.6.egg/keras/engine/network.py", line 1230, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.6/site-packages/Keras-2.3.1-py3.6.egg/keras/engine/saving.py", line 1224, in load_weights_from_hdf5_group
    reshape=reshape)
  File "/usr/local/lib/python3.6/site-packages/Keras-2.3.1-py3.6.egg/keras/engine/saving.py", line 980, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "<__array_function__ internals>", line 6, in transpose
  File "/usr/local/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 650, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/usr/local/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array
```

Something to clarify; it works just fine with the default version and internet connection, it only gives me the error when I change the path file to the weight files which were downloaded as you suggested above.

**Comment by ntustison** [comment]
Then it's probably the wrong weights I had you download.  If you were able to run it fine using the internet connection, take the weights that were downloaded during that run and try that file.

**Comment by asoroosh** [comment]
Yup! Works just fine now! Thank you!
