### ISSUE TITLE
doBrainExtraction.py raises ValueError from np.asarray subtraction

### ISSUE THREAD

**Issue by trgosselin** [ANTsRNet/BrainExtraction#7]
@stnava

Running within container on t2.xlarge EC2 instance with Amazon Linux 2 OS.  

Input is a T1w nii.gz and uses the S_template3_resampled.nii.gz template provided in the repo. 

The call to the script:

python doBrainExtraction.py <input_path> <template_path>

**Error Message:**
```
Traceback (most   recent call last):
  File "brain_extraction/doBrainExtraction.py", line 73, in   <module>
    translation = np.asarray(center_of_mass_image) -   np.asarray(center_of_mass_template)
ValueError: operands could not be   broadcast together with shapes (4,) (3,)
```

**Dockerfile**
```
FROM python:3.7-slim-buster
LABEL maintainer="tgosselin"

RUN mkdir /src
WORKDIR /src

RUN mkdir /output
RUN mkdir /data

# Setup pypi python packages
RUN apt-get update && \
    apt-get install -y cmake pkg-config git

RUN pip install numpy keras boto3
RUN pip install --upgrade tensorflow tensorflow-probability

# Set up external packages
RUN pip install antspyx

COPY ANTsPyNet /src/ANTsPyNet
WORKDIR /src/ANTsPyNet
RUN python setup.py install

RUN mkdir /app
COPY src /app/src
COPY BrainExtraction/Scripts /app/src/brain_extraction
COPY BrainExtraction/Data/Template /app/src/template
RUN chmod +x /app/src/brain_extraction/doBrainExtraction.py
WORKDIR /app/src
```

**Full Logs**
```
2020-06-24 15:26:53.091635: W   tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load   dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared   object file: No such file or directory
2020-06-24   15:26:53.091691: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed   call to cuInit: UNKNOWN ERROR (303)
2020-06-24 15:26:53.091714: I   tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does   not appear to be running on this host (ip-172-31-24-112):   /proc/driver/nvidia/version does not exist
2020-06-24   15:26:53.091982: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your   CPU supports instructions that this TensorFlow binary was not compiled to   use: AVX2 AVX512F FMA
2020-06-24   15:26:53.109531: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102]   CPU Frequency: 2499995000 Hz
2020-06-24 15:26:53.109869: I   tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f48e8000b20   initialized for platform Host (this does not guarantee that XLA will be   used). Devices:
2020-06-24   15:26:53.109895: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default   Version
Using   TensorFlow backend.
Reading reorientation template   /app/src/template/S_template3_resampled.nii.gz
(elapsed time:  0.18723797798156738  seconds)
Loading   weights file
(elapsed time:  1.1513798236846924  seconds)
Reading    /data/sub-005S0572_1_T1w.nii.gz
(elapsed time:  0.8522129058837891  seconds)
Normalizing   to template
Traceback (most recent call last):
File   "brain_extraction/doBrainExtraction.py", line 73, in <module>
translation =   np.asarray(center_of_mass_image) - np.asarray(center_of_mass_template)
ValueError: operands could not be   broadcast together with shapes (4,) (3,)
Uploading   to S3
Traceback   (most recent call last):
File "batch.py", line 87, in   <module>
be.main()
File "batch.py", line 71, in main
self.upload_output()
File "batch.py", line 65, in   upload_output
self.output_path()
File   "/usr/local/lib/python3.7/site-packages/boto3/s3/inject.py", line   131, in upload_file
extra_args=ExtraArgs, callback=Callback)
File   "/usr/local/lib/python3.7/site-packages/boto3/s3/transfer.py", line   279, in upload_file
future.result()
File   "/usr/local/lib/python3.7/site-packages/s3transfer/futures.py",   line 106, in result
return self._coordinator.result()
File   "/usr/local/lib/python3.7/site-packages/s3transfer/futures.py",   line 265, in result
raise self._exception
File   "/usr/local/lib/python3.7/site-packages/s3transfer/tasks.py", line   255, in _main
self._submit(transfer_future=transfer_future, **kwargs)
File   "/usr/local/lib/python3.7/site-packages/s3transfer/upload.py", line   549, in _submit
upload_input_manager.provide_transfer_size(transfer_future)
File   "/usr/local/lib/python3.7/site-packages/s3transfer/upload.py", line   237, in provide_transfer_size
transfer_future.meta.call_args.fileobj))
File   "/usr/local/lib/python3.7/site-packages/s3transfer/utils.py", line   245, in get_file_size
return os.path.getsize(filename)
File "/usr/local/lib/python3.7/genericpath.py", line 50, in   getsize
return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file   or directory: '/output/sub-005S0572_1_T1w_be.nii.gz'
```

**Comment by ntustison** [comment]
Sorry about this.  I need to remove many of the ANTsXNet Apps that I've moved to the actual repository.  Please use the [function](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/brain_extraction.py) in the actual antspynet library.

**Comment by stnava** [comment]
@trgosselin do you have an example image (the T1w) that fails? @ntustison  this may be a garbage in / garbage out problem - also, is his previously downloaded template the same as the one downloaded on the fly?

**Comment by ntustison** [comment]
Yeah, I'm pretty sure it's the same template so I would think that the "app" should still work.

**Comment by stnava** [comment]
I suppose another potential issue is that the release lags the repo.  

this 

ValueError: operands could not be   broadcast together with shapes (4,) (3,)


also suggests something is being treated as 4D.

**Comment by ntustison** [comment]
Yeah, that's weird.  Easiest would be to see the data for myself.

**Comment by stnava** [comment]
yes if we had an example image, could also cross-check with ANTsR

**Comment by trgosselin** [comment]
[sub-005S0572_1_T1w.nii.gz](https://github.com/ANTsXNet/BrainExtraction/files/4827662/sub-005S0572_1_T1w.nii.gz)
Here is one that failed

**Comment by stnava** [comment]
ok - my guess was correct.  this image is 4D.   need to figure out some error handling for that.

**Comment by ntustison** [comment]
That check is currently in the function 

```
>>> mask = antspynet.brain_extraction( t1, modality = "t1", verbose = True )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ntustison/Pkg/ANTsPyNet/antspynet/utilities/brain_extraction.py", line 77, in brain_extraction
    raise ValueError( "Image dimension must be 3." )
ValueError: Image dimension must be 3.
```

**Comment by stnava** [comment]
so a lag from source, then.

**Comment by ntustison** [comment]
Yeah, definitely.  But I haven't thought enough about what to do with an App when we move the functionality to the actual repo.  Something like brian extraction is so simple in terms of calling the function from e.g., antspynet that it seems that keeping the App around, even if we update it to call the repo function, would just make the ecosystem cluttered.  Probably for now I'll update to the function call but ultimately would lean towards deleting it.

**Comment by ntustison** [comment]
"brian extraction"
